#      _                _
#   __| | __ _  ___  __| |
#  / _` |/ _` |/ _ \/ _` |
# | (_| | (_| |  __/ (_| |
#  \__,_|\__,_|\___|\__,_|
#
# Copyright (C) 2023 @daeuniverse <https://github.com/daeuniverse>
#
# This is a open-source software, liscensed under the MIT License.
# See /License for more information.

name: Synchronize Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 */15 * *"

jobs:
  sync-dae-core:
    uses: daeuniverse/ci-seed-jobs/.github/workflows/sync-upstream.yml@master
    with:
      submodule-name: wing
    secrets: inherit
